### ISSUE TITLE
Windows11 21H2 Time's font and location error

### ISSUE THREAD

**Issue by doublemarkpro** [acoollevel/desktop-clock#3]
**Describe the bug**
PC version is Windows 11, 21H2, 22000.613
Screen is 2k with 2560*1440
Python version is 3.10.4
pythonw had been added to PATH

**Screenshots**
![image](https://user-images.githubusercontent.com/24858774/170639925-38d5ae8d-3aac-4b02-8db6-cdc088e9fc78.png)

The Time displayed at center of the screen and the font is different from yours.

Is there anyway to put the clock at top center of the screen and change the font to your style?

Thanks.

**Comment by doublemarkpro** [comment]
Make source tkintertime place at y=60 and tkinterdate at y =120.
Font can be changed through code too.

**Comment by Dhyfer1** [comment]
> Make source tkintertime place at y=60 and tkinterdate at y =120. Font can be changed through code too.

I need more details. What file did you edit and how? I want to change the font, size and position, but I don't know how to do it?

**Comment by Dhyfer1** [comment]
@acoollevel Please can you tell me how can I customize the height and position of the time and date?
